name: End to End Tests - Prod

on:
  # Runs every Tuesday and Thursday at 2pm IST
  schedule:
    - cron:  '30 8 * * 2,4'
  pull_request:
    types: [assigned,  opened,  synchronize,  reopened]

jobs:
  end-to-end-test-prod:
    runs-on: macos-latest
    environment: End to End Test - Production
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install dependencies
        run: npm install --prefix cypress
      - name: Prepare for end to end tests
        run: npm run setup_e2e_test
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          record: true
          browser: chrome
          tag: ${{ secrets.E2E_TESTS_ENV }}
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
      COMMIT_INFO_MESSAGE: ${{github.event.pull_request.title}}
      COMMIT_INFO_SHA: ${{github.event.pull_request.head.sha}}
      APP_URL: ${{ secrets.APP_URL }}
      API_URL: ${{ secrets.API_URL }}
      E2E_TESTS_CLIENT_ID: ${{ secrets.E2E_TESTS_CLIENT_ID }}
      E2E_TESTS_WORKSPACE_ID_1: ${{ secrets.E2E_TESTS_WORKSPACE_ID_1 }}
      E2E_TESTS_WORKSPACE_ID_2: ${{ secrets.E2E_TESTS_WORKSPACE_ID_2 }}
      E2E_TESTS_ENV: ${{ secrets.E2E_TESTS_ENV }}
      E2E_TESTS_REFRESH_TOKEN_1: ${{ secrets.E2E_TESTS_REFRESH_TOKEN_1 }}
      E2E_TESTS_ORG_ID_1: ${{ secrets.E2E_TESTS_ORG_ID_1 }}
      E2E_TESTS_NS_ACCOUNT_ID_1: ${{ secrets.E2E_TESTS_NS_ACCOUNT_ID_1}}
      E2E_TESTS_NS_TOKEN_ID_1: ${{secrets.E2E_TESTS_NS_TOKEN_ID_1}}
      E2E_TESTS_NS_TOKEN_SECRET_1: ${{secrets.E2E_TESTS_NS_TOKEN_SECRET_1}}
      E2E_TESTS_REFRESH_TOKEN_2: ${{ secrets.E2E_TESTS_REFRESH_TOKEN_2 }}
      E2E_TESTS_ORG_ID_2: ${{ secrets.E2E_TESTS_ORG_ID_2 }}
      E2E_TESTS_NS_ACCOUNT_ID_2: ${{ secrets.E2E_TESTS_NS_ACCOUNT_ID_2}}
      E2E_TESTS_NS_TOKEN_ID_2: ${{secrets.E2E_TESTS_NS_TOKEN_ID_2}}
      E2E_TESTS_NS_TOKEN_SECRET_2: ${{secrets.E2E_TESTS_NS_TOKEN_SECRET_2}}
